"""add memory embedding

Revision ID: ac1727277053
Revises: a18882263654
Create Date: 2026-09-01 19:51:25.584658

"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import pgvector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac1727277053'
down_revision: Union[str, Sequence[str], None] = 'a18882263654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_memories', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_memories", "embedding")
    # ### end Alembic commands ###
