"""add agent memories

Revision ID: a18882263654
Revises: 3b35e14144cf
Create Date: 2026-09-01 15:41:38.839826

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a18882263654"
down_revision: str | Sequence[str] | None = "3b35e14144cf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_memories",
        sa.Column("repository", sa.String(length=500), nullable=False),
        sa.Column("memory_type", sa.Enum("EPISODIC", "SEMANTIC", name="agent_memory_type_enum"), nullable=False),
        sa.Column("memory_key", sa.String(length=500), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source_agent_run_id", sa.UUID(), nullable=True),
        sa.Column("importance", sa.Integer(), nullable=False),
        sa.Column("memory_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["source_agent_run_id"], ["agent_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_memories_id"), "agent_memories", ["id"], unique=False)
    op.create_index(op.f("ix_agent_memories_is_active"), "agent_memories", ["is_active"], unique=False)
    op.create_index(op.f("ix_agent_memories_memory_key"), "agent_memories", ["memory_key"], unique=False)
    op.create_index(op.f("ix_agent_memories_memory_type"), "agent_memories", ["memory_type"], unique=False)
    op.create_index(op.f("ix_agent_memories_repository"), "agent_memories", ["repository"], unique=False)
    op.create_index(op.f("ix_agent_memories_source_agent_run_id"), "agent_memories", ["source_agent_run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_memories_source_agent_run_id"), table_name="agent_memories")
    op.drop_index(op.f("ix_agent_memories_repository"), table_name="agent_memories")
    op.drop_index(op.f("ix_agent_memories_memory_type"), table_name="agent_memories")
    op.drop_index(op.f("ix_agent_memories_memory_key"), table_name="agent_memories")
    op.drop_index(op.f("ix_agent_memories_is_active"), table_name="agent_memories")
    op.drop_index(op.f("ix_agent_memories_id"), table_name="agent_memories")
    op.drop_table("agent_memories")
    sa.Enum(
        "EPISODIC",
        "SEMANTIC",
        name="agent_memory_type_enum",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
