"""add memory expiration

Revision ID: 8d72d7a75fd4
Revises: ac1727277053
Create Date: 2026-09-01 23:24:38.216137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d72d7a75fd4'
down_revision: Union[str, Sequence[str], None] = 'ac1727277053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_memories', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_agent_memories_expires_at'), 'agent_memories', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_memories_expires_at'), table_name='agent_memories')
    op.drop_column('agent_memories', 'expires_at')
    # ### end Alembic commands ###
